force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <description>Basic vehicle type</description>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>ID#{000000}</displayFormat>
        <label>Vehicle ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_Last_Maintenance_Date__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Last_Maintenance_Date__c</fullName>
    <description>Vehicle Last Maintenance Date</description>
    <inlineHelpText>Last date of vehicle maintenance</inlineHelpText>
    <label>Vehicle Last Maintenance Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_model_description__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_model_description__c</fullName>
    <formula>Vehicle_Manufacturer__c &amp; &quot;:   &quot; &amp; Vehicle_model__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Vehicle model description</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_plate_number__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_plate_number__c</fullName>
    <description>replace with vehicle number object</description>
    <label>Vehicle plate number</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_Status__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Status__c</fullName>
    <label>Vehicle Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Not Available</fullName>
            </value>
            <value>
                <fullName>At Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/recordTypes/Vehicle.recordType-meta.xml
<RecordType>
    <fullName>Vehicle</fullName>
    <active>true</active>
    <label>Vehicle</label>
</RecordType>

force-app/main/default/classes/VehicleViewControllerTest.cls
@isTest
public with sharing class VehicleViewControllerTest {
	/**
	 * positive test to check filtering by status
	 * It is expected that four values will be obtained without filtering, and two with it.
	 */
	@isTest
	public static void filteredVehicleRequest_test() {
		//--------------------------     begin data generation     --------------------------
		//prepare data
		List<Vehicle__c> availableTest = VehicleTrigger_TestDataFactory.createVehicles(
			new List<String>{ 'CAR' },
			new List<String>{ 'model_1' },
			new List<String>{ 'TX123' },
			new List<String>{ 'Available' },
			new List<Integer>{ 0 },
			new List<Integer>{ 1, 2 }
		);
		List<Vehicle__c> notAvailableTest = VehicleTrigger_TestDataFactory.createVehicles(
			new List<String>{ 'CAR' },
			new List<String>{ 'model_1' },
			new List<String>{ 'TX123' },
			new List<String>{ 'Not Available' },
			new List<Integer>{ 0 },
			new List<Integer>{ 1, 2 }
		);

		List<Vehicle__c> newList = new List<Vehicle__c>();
		newList.addAll(availableTest);
		newList.addAll(notAvailableTest);

		for (Vehicle__c vehicle : newList) {
			vehicle.recalculateFormulas();
		}
		insert newList;
		//--------------------------     end data generation     --------------------------

		//--------------------------   insert test     --------------------------

		Test.startTest();
		List<Vehicle__c> allList = VehicleViewController.getRecords(VehicleViewController.ALL);
		List<Vehicle__c> availableList = VehicleViewController.getRecords(VehicleViewController.AVAILABLE_STATUS);

		System.assertEquals(
			newList.size(),
			allList.size(),
			'Expected to get all records, but difference in number of generated vehicles, in count of ' +
			newList.size() +
			',  and number of requested in VehicleViewController vehicles, in cou   nt of ' +
			allList.size()
		);

		System.assertEquals(
			availableTest.size(),
			availableList.size(),
			'Expected to get available records, but difference in number of generated vehicles, in count of ' +
			availableList.size() +
			',  and number of requested in VehicleViewController vehicles, in cou   nt of ' +
			availableList.size()
		);

		Test.stopTest();
	}

	@isTest
	public static void wiredVehicleRequest() {
		//--------------------------     begin data generation     --------------------------
		//prepare data
		List<Vehicle__c> testVehicleList = VehicleTrigger_TestDataFactory.createVehicles(
			new List<String>{ 'CAR' },
			new List<String>{ 'model_1' },
			new List<String>{ 'TX123' },
			new List<String>{ 'Available' },
			new List<Integer>{ 0 },
			new List<Integer>{ 2 }
		);
		for (Vehicle__c vehicle : testVehicleList) {
			vehicle.recalculateFormulas();
		}
		insert testVehicleList;
		//--------------------------     end data generation     --------------------------

		Test.startTest();
		System.assert(testVehicleList.size() == 1, 'size');
		Vehicle__c testVehicle = testVehicleList.get(0);
		System.debug('test vehicle' + testVehicle);
		List<VehicleViewController.Vehicle> responce = VehicleViewController.getWrappedRecords(
			VehicleViewController.ALL
		);
		System.assert(responce.size() == testVehicleList.size(), 'msg');
		VehicleViewController.Vehicle target = responce.get(0);
		System.debug('target vehicle' + target);
		System.assertEquals(testVehicle.Id, target.id);
		System.assertEquals(testVehicle.Vehicle_model_description__c, target.vehicleDescription);
		System.assertEquals(testVehicle.Vehicle_Status__c, target.status);
		System.assertEquals(testVehicle.Vehicle_plate_number__c, target.plateNumber);
		System.assertEquals(testVehicle.Vehicle_Last_Maintenance_Date__c, target.lastMaintenanceDate);

		Test.stopTest();
	}
}