force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <description>Basic vehicle type</description>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>ID#{000000}</displayFormat>
        <label>Vehicle ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_driver__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_driver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup for the contact of vehicle driver</description>
    <inlineHelpText>Vehicle driver conatct</inlineHelpText>
    <label>Vehicle driver</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Vehicle</relationshipLabel>
    <relationshipName>Vehicle</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_driver_contact_phone_reader__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_driver_contact_phone_reader__c</fullName>
    <formula>IF(NOT ISBLANK( Vehicle_driver__r.Phone) ,  Vehicle_driver__r.Phone,
    IF(NOT ISBLANK( Vehicle_driver__r.MobilePhone ) ,  Vehicle_driver__r.MobilePhone,
        IF(NOT ISBLANK( Vehicle_driver__r.OtherPhone ) ,  Vehicle_driver__r.OtherPhone, 
            IF(NOT ISBLANK( Vehicle_driver__r.AssistantPhone ) ,  Vehicle_driver__r.AssistantPhone, 
                IF(NOT ISBLANK( Vehicle_driver__r.HomePhone ) ,  Vehicle_driver__r.HomePhone,&quot;no contact phone&quot;)
            )
        )
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Vehicle driver contact phone</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_Last_Maintenance_Date__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Last_Maintenance_Date__c</fullName>
    <description>Vehicle Last Maintenance Date</description>
    <inlineHelpText>Last date of vehicle maintenance</inlineHelpText>
    <label>Vehicle Last Maintenance Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_model_description__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_model_description__c</fullName>
    <formula>Vehicle_Manufacturer__c &amp; &quot;:   &quot; &amp; Vehicle_model__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Vehicle model description</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_plate_number__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_plate_number__c</fullName>
    <description>replace with vehicle number object</description>
    <label>Vehicle plate number</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_Status__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Status__c</fullName>
    <label>Vehicle Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Not Available</fullName>
            </value>
            <value>
                <fullName>At Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Type__c</fullName>
    <label>Vehicle Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Car</fullName>
                <default>true</default>
                <label>Car</label>
            </value>
            <value>
                <fullName>Truck</fullName>
            </value>
            <value>
                <fullName>Van</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/VehicleViewController.cls
public with sharing class VehicleViewController {
	@AuraEnabled(cacheable=true)
	public static List<Vehicle__c> getRecords() {
		// return [
		// 	SELECT Id, Vehicle_model_description__c, Vehicle_plate_number__c
		// 	FROM Vehicle__c
		// 	WITH SECURITY_ENFORCED
		// ];
		return [
			SELECT
				Id,
				Vehicle_model_description__c,
				Vehicle_plate_number__c,
				Vehicle_driver__r.Name,
				Vehicle_driver_contact_phone_reader__c,
				Vehicle_Status__c,
				Vehicle_Type__c,
				Vehicle_Last_Maintenance_Date__c
			FROM Vehicle__c
			WITH SECURITY_ENFORCED
		];
	}
}