force-app/main/default/objects/Maintenance__c/Maintenance__c.object-meta.xml
<CustomObject>
    <label>Maintenance</label>
    <nameField>
        <displayFormat>#{0}</displayFormat>
        <label>Maintenance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Maintenance&apos;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Maintenance__c/fields/Maintenance_date__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_date__c</fullName>
    <description>Maintenance date</description>
    <label>Maintenance date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Maintenance__c/fields/Maintenance_from_date__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_from_date__c</fullName>
    <description>Maintenance is available from this date</description>
    <label>Maintenance from date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Maintenance__c/fields/Maintenance_Service__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_Service__c</fullName>
    <label>Maintenance Service</label>
    <referenceTo>Maintenance_Service__c</referenceTo>
    <relationshipLabel>Maintenance&apos;s</relationshipLabel>
    <relationshipName>Maintenance_s</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Maintenance__c/fields/Maintenance_status__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_status__c</fullName>
    <label>Maintenance status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>POSTPONED, did not appear for inspection</fullName>
            </value>
            <value>
                <fullName>OK, all good</fullName>
            </value>
            <value>
                <fullName>OK, in-line repair</fullName>
            </value>
            <value>
                <fullName>BAD, capital repair</fullName>
            </value>
            <value>
                <fullName>BAD, only for spare parts</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Maintenance__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <description>car that was serviced</description>
    <inlineHelpText>car that was serviced</inlineHelpText>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Maintenance&apos;s</relationshipLabel>
    <relationshipName>Maintenance_s</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Maintenance_Service__c/Maintenance_Service__c.object-meta.xml
<CustomObject>
    <label>Maintenance Service</label>
    <nameField>
        <label>Maintenance Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Maintenance Service</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <description>Basic vehicle type</description>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>ID#{000000}</displayFormat>
        <label>Vehicle ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/MaintenanceViewController.cls
public with sharing class MaintenanceViewController {
	@AuraEnabled(cacheable=true)
	public static List<Maintenance__c> getRecords(Id targetVehicleId) {
		return [
			SELECT Id, Maintenance_from_date__c, Maintenance_date__c, Maintenance_Service__r.Name, Maintenance_status__c
			FROM Maintenance__c
			WHERE Maintenance__c.Vehicle__c = :targetVehicleId
			WITH SECURITY_ENFORCED
		];
	}

	@AuraEnabled(cacheable=true)
	public static List<Maintenance> getWrappedRecords(Id targetVehicleId) {
		try {
			List<Maintenance__c> maintenances = getRecords(targetVehicleId);
			List<Maintenance> result = new List<Maintenance>();
			for (Maintenance__c value : maintenances) {
				Maintenance target = new Maintenance();
				target.id = value.Id;
				target.fromDate = value.Maintenance_from_date__c;
				target.actualDate = value.Maintenance_date__c;
				target.service = value.Maintenance_Service__r.Name;
				target.status = value.Maintenance_status__c;
				result.add(target);
			}

			return result;
		} catch (Exception e) {
			throw new AuraHandledException(e.getMessage());
		}
	}

	public class Maintenance {
		@AuraEnabled
		public Id id;
		@AuraEnabled
		public Date fromDate;
		@AuraEnabled
		public Date actualDate;
		@AuraEnabled
		public String service;
		@AuraEnabled
		public String status;
	}
}