force-app/main/default/objects/Maintenance__c/Maintenance__c.object-meta.xml
<CustomObject>
    <label>Maintenance</label>
    <nameField>
        <displayFormat>#{0}</displayFormat>
        <label>Maintenance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Maintenance&apos;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Maintenance__c/fields/Maintenance_from_date__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_from_date__c</fullName>
    <description>Maintenance is available from this date</description>
    <label>Maintenance from date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Maintenance__c/fields/Maintenance_Service__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_Service__c</fullName>
    <label>Maintenance Service</label>
    <referenceTo>Maintenance_Service__c</referenceTo>
    <relationshipLabel>Maintenance&apos;s</relationshipLabel>
    <relationshipName>Maintenance_s</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Maintenance__c/fields/Maintenance_status__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_status__c</fullName>
    <label>Maintenance status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>POSTPONED, did not appear for inspection</fullName>
            </value>
            <value>
                <fullName>OK, all good</fullName>
            </value>
            <value>
                <fullName>OK, in-line repair</fullName>
            </value>
            <value>
                <fullName>BAD, capital repair</fullName>
            </value>
            <value>
                <fullName>BAD, only for spare parts</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Maintenance__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <description>car that was serviced</description>
    <inlineHelpText>car that was serviced</inlineHelpText>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Maintenance&apos;s</relationshipLabel>
    <relationshipName>Maintenance_s</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Maintenance_Service__c/Maintenance_Service__c.object-meta.xml
<CustomObject>
    <label>Maintenance Service</label>
    <nameField>
        <label>Maintenance Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Maintenance Service</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <description>Basic vehicle type</description>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>ID#{000000}</displayFormat>
        <label>Vehicle ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_driver__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_driver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup for the contact of vehicle driver</description>
    <inlineHelpText>Vehicle driver conatct</inlineHelpText>
    <label>Vehicle driver</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Vehicle</relationshipLabel>
    <relationshipName>Vehicle</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_Last_Maintenance__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Last_Maintenance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle Last Maintenance</label>
    <referenceTo>Maintenance__c</referenceTo>
    <relationshipLabel>Vehicle</relationshipLabel>
    <relationshipName>Vehicle_Last_Maintenance</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_Last_Maintenance_Date__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Last_Maintenance_Date__c</fullName>
    <description>Vehicle Last Maintenance Date</description>
    <inlineHelpText>Last date of vehicle maintenance</inlineHelpText>
    <label>Vehicle Last Maintenance Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_Manufacturer__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Manufacturer__c</fullName>
    <label>Vehicle Manufacturer</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_model__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_model__c</fullName>
    <label>Vehicle model</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_Next_Maintenance_Date__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Next_Maintenance_Date__c</fullName>
    <description>Vehicle Next Maintenance Date</description>
    <inlineHelpText>Next sheduled date of vehicle maintenance</inlineHelpText>
    <label>Vehicle Next Maintenance Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_plate_number__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_plate_number__c</fullName>
    <description>replace with vehicle number object</description>
    <label>Vehicle plate number</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_Status__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Status__c</fullName>
    <label>Vehicle Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Not Available</fullName>
            </value>
            <value>
                <fullName>At Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/recordTypes/Vehicle.recordType-meta.xml
<RecordType>
    <fullName>Vehicle</fullName>
    <active>true</active>
    <label>Vehicle</label>
</RecordType>

force-app/main/default/classes/VehicleTrigger_Test_Helper.cls
public class VehicleTrigger_Test_Helper {
	//defined number of generated records
	static final Integer NUMBER_OF_DRIVERS_WITH_EMAIL = 100;
	static final Integer NUMBER_OF_DRIVERS_WITHOUT_EMAIL = 100;

	static final Integer NUMBER_OF_VALID_RECORDS_WITH_LAST_MAINTENANCE_WITHOUT_DRIVER = 100;
	static final Integer NUMBER_OF_VALID_RECORDS_WITH_LAST_MAINTENANCE_WITH_DRIVER_WITH_EMAIL = NUMBER_OF_DRIVERS_WITH_EMAIL;
	static final Integer NUMBER_OF_VALID_RECORDS_WITH_LAST_MAINTENANCE_WITH_DRIVER_WITHOUT_EMAIL = NUMBER_OF_DRIVERS_WITHOUT_EMAIL;
	static final Integer NUMBER_OF_VALID_RECORDS_WITHOUT_LAST_MAINTENANCE_WITHOUT_DRIVER = 100;

	public static final Integer NUMBER_OF_VALID_RECORDS = 400;
	public static final Integer NUMBER_OF_MESSAGES = 100;
	/**
	 * helper method to do many records
	 */
	public static void makeManyVehicles() {
		//contacts
		//every contact will get message about two vehicles
		List<Contact> driverWithEmail = VehicleTrigger_TestDataFactory.createContacts(
			VehicleTrigger_TestDataFactory.createContactsNames('driverWithEmail', NUMBER_OF_DRIVERS_WITH_EMAIL),
			new List<String>{ 'email@test.com' }
		);
		insert driverWithEmail;
		List<Contact> driverWithoutEmail = VehicleTrigger_TestDataFactory.createContacts(
			VehicleTrigger_TestDataFactory.createContactsNames('driverWithoutEmail', NUMBER_OF_DRIVERS_WITHOUT_EMAIL)
		);
		insert driverWithoutEmail;
		//vehicles
		List<Vehicle__c> vehicleWithLastMaintenanceList = new List<Vehicle__c>();
		vehicleWithLastMaintenanceList.addAll(createVehicles(null));
		vehicleWithLastMaintenanceList.addAll(createVehicles(driverWithEmail));
		vehicleWithLastMaintenanceList.addAll(createVehicles(driverWithoutEmail));
		System.debug('vehicleWithLastMaintenanceList size ' + vehicleWithLastMaintenanceList.size());
		insert vehicleWithLastMaintenanceList;
		List<Vehicle__c> vehicleWithoutLastMaintenanceList = createVehicles(null);
		System.debug('vehicleWithoutLastMaintenanceList size ' + vehicleWithoutLastMaintenanceList.size());
		insert vehicleWithoutLastMaintenanceList;

		//maintenance service, firsat wiill be default service, secont is usual
		List<Maintenance_Service__c> maintenanceServiceList = VehicleTrigger_TestDataFactory.createMaintenanceService(
			2,
			1
		);

		insert maintenanceServiceList;
		//maintenance
		List<Maintenance__c> maintenanceList = VehicleTrigger_TestDataFactory.createMaintemance(
			new List<Maintenance_Service__c>{ maintenanceServiceList.get(1) },
			new List<Integer>{ 1 },
			new List<String>{ 'Scheduled' },
			vehicleWithLastMaintenanceList
		);
		System.debug('maintenanceList size ' + maintenanceList.size());
		insert maintenanceList;

		for (Vehicle__c vehicle : vehicleWithLastMaintenanceList) {
			for (Maintenance__c maintenance : maintenanceList) {
				if (maintenance.Vehicle__c == vehicle.Id) {
					vehicle.Vehicle_Last_Maintenance__c = maintenance.Id;
				}
			}
		}
		System.debug('vehicleWithLastMaintenanceList size (before update)' + vehicleWithLastMaintenanceList.size());

		update vehicleWithLastMaintenanceList;
	}

	static List<Vehicle__c> createVehicles(List<Contact> drivers) {
		if (drivers != null) {
			return VehicleTrigger_TestDataFactory.createVehicles(
				new List<String>{ 'CAR' },
				new List<String>{ 'model_1' },
				new List<String>{ 'TX123' },
				new List<String>{ 'Available' },
				new List<Integer>{ 0 },
				new List<Integer>{ 2 },
				drivers
			);
		} else {
			return VehicleTrigger_TestDataFactory.createVehicles(
				new List<String>{ 'CAR' },
				VehicleTrigger_TestDataFactory.createContactsNames('model', 100),
				new List<String>{ 'TX123' },
				new List<String>{ 'Available' },
				new List<Integer>{ 0 },
				new List<Integer>{ 2 }
			);
		}
	}
	/**
	 * helper method to do one records
	 */
	public static Vehicle__c makeSingleVehicle(Boolean withDriver, Boolean withMaintenance) {
		Contact driver;
		Maintenance__c maintenance;

		if (withDriver) {
			driver = new Contact();
			driver.LastName = 'testDriver';
			driver.Email = 'kamkaliev@gmail.com';
			insert driver;
		}
		//default service
		List<Maintenance_Service__c> serviceList = VehicleTrigger_TestDataFactory.createMaintenanceService(1, 1);
		insert serviceList;
		Vehicle__c vehicle = new Vehicle__c();
		vehicle.Vehicle_Manufacturer__c = 'testCar';
		vehicle.Vehicle_model__c = 'model1';
		vehicle.Vehicle_plate_number__c = 'TX456';
		vehicle.Vehicle_Status__c = 'Available';
		vehicle.Vehicle_Last_Maintenance_Date__c = Date.today();
		vehicle.Vehicle_Next_Maintenance_Date__c = Date.today() + 7;
		vehicle.Vehicle_driver__c = driver.Id;
		// insert vehicle;
		vehicle.recalculateFormulas();
		insert vehicle;

		if (withMaintenance) {
			maintenance = new Maintenance__c();
			maintenance.Maintenance_Service__c = serviceList.get(0).Id;
			maintenance.Maintenance_from_date__c = Date.today() + 7;
			maintenance.Maintenance_status__c = 'Scheduled';
			maintenance.Vehicle__c = vehicle.Id;
			maintenance.recalculateFormulas();
			insert maintenance;
			vehicle.Vehicle_Last_Maintenance__c = maintenance.Id;
			update vehicle;
		}
		return vehicle;
	}
}