force-app/main/default/objects/Maintenance__c/Maintenance__c.object-meta.xml
<CustomObject>
    <label>Maintenance</label>
    <nameField>
        <displayFormat>#{0}</displayFormat>
        <label>Maintenance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Maintenance&apos;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Maintenance__c/fields/Maintenance_Service__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_Service__c</fullName>
    <label>Maintenance Service</label>
    <referenceTo>Maintenance_Service__c</referenceTo>
    <relationshipLabel>Maintenance&apos;s</relationshipLabel>
    <relationshipName>Maintenance_s</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Maintenance__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <description>car that was serviced</description>
    <inlineHelpText>car that was serviced</inlineHelpText>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Maintenance&apos;s</relationshipLabel>
    <relationshipName>Maintenance_s</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Maintenance_Service__c/Maintenance_Service__c.object-meta.xml
<CustomObject>
    <label>Maintenance Service</label>
    <nameField>
        <label>Maintenance Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Maintenance Service</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <description>Basic vehicle type</description>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>ID#{000000}</displayFormat>
        <label>Vehicle ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_Last_Maintenance__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Last_Maintenance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle Last Maintenance</label>
    <referenceTo>Maintenance__c</referenceTo>
    <relationshipLabel>Vehicle</relationshipLabel>
    <relationshipName>Vehicle_Last_Maintenance</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_Last_Maintenance_Date__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Last_Maintenance_Date__c</fullName>
    <description>Vehicle Last Maintenance Date</description>
    <inlineHelpText>Last date of vehicle maintenance</inlineHelpText>
    <label>Vehicle Last Maintenance Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_Next_Maintenance_Date__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Next_Maintenance_Date__c</fullName>
    <description>Vehicle Next Maintenance Date</description>
    <inlineHelpText>Next sheduled date of vehicle maintenance</inlineHelpText>
    <label>Vehicle Next Maintenance Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/recordTypes/Vehicle.recordType-meta.xml
<RecordType>
    <fullName>Vehicle</fullName>
    <active>true</active>
    <label>Vehicle</label>
</RecordType>

force-app/main/default/triggers/VehicleTrigger_Test.cls
@isTest
public with sharing class VehicleTrigger_Test {
	static final Integer numderOfDriverWithEmail = 100;
	static final Integer numderOfDriverWithoutEmail = 100;

	static final Integer numberOfInvalidRecords = 100;

	static final Integer numberOfValidRecords_WithLastMaintenance_WithoutDriver = 100;
	static final Integer numberOfValidRecords_WithLastMaintenance_WithDriver_WithEmail = numderOfDriverWithEmail;
	static final Integer numberOfValidRecords_WithLastMaintenance_WithDriver_WithoutEmail = numderOfDriverWithoutEmail;
	static final Integer numberOfValidRecords_WithoutLastMaintenance_WithoutDriver = 100;

	static final Integer numberOfValidRecords = 400;
	static final Integer numberOfMessages = 100;

	static void makeData() {
		//contacts
		//every contact will get message about two vehicles
		List<Contact> driverWithEmail = VehicleTrigger_TestDataFactory.createContacts(
			VehicleTrigger_TestDataFactory.createContactsNames('driverWithEmail', numderOfDriverWithEmail),
			new List<String>{ 'email@test.com' }
		);
		insert driverWithEmail;
		List<Contact> driverWithoutEmail = VehicleTrigger_TestDataFactory.createContacts(
			VehicleTrigger_TestDataFactory.createContactsNames('driverWithoutEmail', numderOfDriverWithoutEmail)
		);
		insert driverWithoutEmail;
		//vehicles
		List<Vehicle__c> vehicleWithLastMaintenanceList = new List<Vehicle__c>();
		vehicleWithLastMaintenanceList.addAll(createVehicles(null));
		vehicleWithLastMaintenanceList.addAll(createVehicles(driverWithEmail));
		vehicleWithLastMaintenanceList.addAll(createVehicles(driverWithoutEmail));
		System.debug('vehicleWithLastMaintenanceList size ' + vehicleWithLastMaintenanceList.size());
		insert vehicleWithLastMaintenanceList;
		List<Vehicle__c> vehicleWithoutLastMaintenanceList = createVehicles(null);
		System.debug('vehicleWithoutLastMaintenanceList size ' + vehicleWithoutLastMaintenanceList.size());
		insert vehicleWithoutLastMaintenanceList;

		//maintenance service, firsat wiill be default service, secont is usual
		List<Maintenance_Service__c> maintenanceServiceList = VehicleTrigger_TestDataFactory.createMaintenanceService(
			2,
			1
		);

		insert maintenanceServiceList;
		//maintenance
		List<Maintenance__c> maintenanceList = VehicleTrigger_TestDataFactory.createMaintemance(
			new List<Maintenance_Service__c>{ maintenanceServiceList.get(1) },
			new List<Integer>{ 1 },
			new List<String>{ 'Scheduled' },
			vehicleWithLastMaintenanceList
		);
		System.debug('maintenanceList size ' + maintenanceList.size());
		insert maintenanceList;

		for (Vehicle__c vehicle : vehicleWithLastMaintenanceList) {
			for (Maintenance__c maintenance : maintenanceList) {
				if (maintenance.Vehicle__c == vehicle.Id) {
					vehicle.Vehicle_Last_Maintenance__c = maintenance.Id;
				}
			}
		}
		System.debug('vehicleWithLastMaintenanceList size (before update)' + vehicleWithLastMaintenanceList.size());

		update vehicleWithLastMaintenanceList;
	}

	static List<Vehicle__c> createVehicles(List<Contact> drivers) {
		if (drivers != null) {
			return VehicleTrigger_TestDataFactory.createVehicles(
				new List<String>{ 'CAR' },
				new List<String>{ 'model_1' },
				new List<String>{ 'TX123' },
				new List<String>{ 'Available' },
				new List<Integer>{ 0 },
				new List<Integer>{ 2 },
				drivers
			);
		} else {
			return VehicleTrigger_TestDataFactory.createVehicles(
				new List<String>{ 'CAR' },
				VehicleTrigger_TestDataFactory.createContactsNames('model', 100),
				new List<String>{ 'TX123' },
				new List<String>{ 'Available' },
				new List<Integer>{ 0 },
				new List<Integer>{ 2 }
			);
		}
	}

	@isTest
	private static void bulk_test() {
		makeData();

		Map<Id, Vehicle__c> vehiclesMap = new Map<Id, Vehicle__c>(
			[
				SELECT
					Id,
					Vehicle_Last_Maintenance_Date__c,
					Vehicle_Next_Maintenance_Date__c,
					Vehicle_Last_Maintenance__c
				FROM Vehicle__c
			]
		);
		System.debug('in test vehiclesMap size ' + vehiclesMap.size());
		System.assert(vehiclesMap.size() == numberOfValidRecords);
		List<Maintenance__c> maintenanceList = [SELECT Id FROM Maintenance__c];
		System.debug('in test maintenanceList size ' + maintenanceList.size());
	}
}