force-app/main/default/objects/Maintenance__c/Maintenance__c.object-meta.xml
<CustomObject>
    <label>Maintenance</label>
    <nameField>
        <displayFormat>#{0}</displayFormat>
        <label>Maintenance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Maintenance&apos;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Maintenance__c/fields/Maintenance_from_date__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_from_date__c</fullName>
    <description>Maintenance is available from this date</description>
    <label>Maintenance from date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Maintenance__c/fields/Maintenance_Service__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_Service__c</fullName>
    <label>Maintenance Service</label>
    <referenceTo>Maintenance_Service__c</referenceTo>
    <relationshipLabel>Maintenance&apos;s</relationshipLabel>
    <relationshipName>Maintenance_s</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Maintenance__c/fields/Maintenance_status__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_status__c</fullName>
    <label>Maintenance status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>POSTPONED, did not appear for inspection</fullName>
            </value>
            <value>
                <fullName>OK, all good</fullName>
            </value>
            <value>
                <fullName>OK, in-line repair</fullName>
            </value>
            <value>
                <fullName>BAD, capital repair</fullName>
            </value>
            <value>
                <fullName>BAD, only for spare parts</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Maintenance__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <description>car that was serviced</description>
    <inlineHelpText>car that was serviced</inlineHelpText>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Maintenance&apos;s</relationshipLabel>
    <relationshipName>Maintenance_s</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Maintenance_Service__c/Maintenance_Service__c.object-meta.xml
<CustomObject>
    <label>Maintenance Service</label>
    <nameField>
        <label>Maintenance Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Maintenance Service</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Maintenance_Service__c/fields/Maintenance_default__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_default__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This maintenance will be selected as default in approval process, if no service was on vehicle</description>
    <inlineHelpText>This maintenance will be selected as default in approval process, if no service was on vehicle</inlineHelpText>
    <label>Maintenance default</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <description>Basic vehicle type</description>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>ID#{000000}</displayFormat>
        <label>Vehicle ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_driver__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_driver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup for the contact of vehicle driver</description>
    <inlineHelpText>Vehicle driver conatct</inlineHelpText>
    <label>Vehicle driver</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Vehicle</relationshipLabel>
    <relationshipName>Vehicle</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_Last_Maintenance_Date__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Last_Maintenance_Date__c</fullName>
    <description>Vehicle Last Maintenance Date</description>
    <inlineHelpText>Last date of vehicle maintenance</inlineHelpText>
    <label>Vehicle Last Maintenance Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_Manufacturer__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Manufacturer__c</fullName>
    <label>Vehicle Manufacturer</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_model__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_model__c</fullName>
    <label>Vehicle model</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_Next_Maintenance_Date__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Next_Maintenance_Date__c</fullName>
    <description>Vehicle Next Maintenance Date</description>
    <inlineHelpText>Next sheduled date of vehicle maintenance</inlineHelpText>
    <label>Vehicle Next Maintenance Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_plate_number__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_plate_number__c</fullName>
    <description>replace with vehicle number object</description>
    <label>Vehicle plate number</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_Status__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Status__c</fullName>
    <label>Vehicle Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Not Available</fullName>
            </value>
            <value>
                <fullName>At Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/recordTypes/Vehicle.recordType-meta.xml
<RecordType>
    <fullName>Vehicle</fullName>
    <active>true</active>
    <label>Vehicle</label>
</RecordType>

force-app/main/default/triggers/VehicleTriggerHelper_TestDataFactory.cls
@isTest
public with sharing class VehicleTriggerHelper_TestDataFactory {
	public static List<Vehicle__c> createVehicles(
		List<String> manufacture,
		List<String> model,
		List<String> plateNumber,
		List<String> status,
		List<Integer> lastDate,
		List<Integer> nextDate
	) {
		List<Vehicle__c> result = new List<Vehicle__c>();

		result = setVehicleField('Vehicle__c', 'Vehicle_Manufacturer__c', result, manufacture);
		result = setVehicleField('Vehicle__c', 'Vehicle_model__c', result, model);
		result = setVehicleField('Vehicle__c', 'Vehicle_plate_number__c', result, plateNumber);
		result = setVehicleField('Vehicle__c', 'Vehicle_Status__c', result, status);

		List<Date> targetLastDate = new List<Date>();
		for (Integer value : lastDate) {
			targetLastDate.add(Date.today() + value);
		}
		result = setVehicleField('Vehicle__c', 'Vehicle_Last_Maintenance_Date__c', result, targetLastDate);

		List<Date> targetNextDate = new List<Date>();
		for (Integer value : nextDate) {
			targetNextDate.add(Date.today() + value);
		}
		result = setVehicleField('Vehicle__c', 'Vehicle_Next_Maintenance_Date__c', result, targetNextDate);

		return result;
	}

	public static List<Vehicle__c> createVehicles(
		List<String> manufacture,
		List<String> model,
		List<String> plateNumber,
		List<String> status,
		List<Integer> lastDate,
		List<Integer> nextDate,
		List<Contact> contacts
	) {
		List<Vehicle__c> result = createVehicles(manufacture, model, plateNumber, status, lastDate, nextDate);
		result = setVehicleField('Vehicle__c', 'Vehicle_driver__c', result, contacts);
		return result;
	}

	public static List<Maintenance__c> createMaintemance(
		List<Maintenance_Service__c> maintenanceService,
		List<Integer> fromDate,
		List<String> status,
		List<Vehicle__c> vehicle
	) {
		List<Maintenance__c> result = new List<Maintenance__c>();
		result = setVehicleField('Maintenance__c', 'Maintenance_Service__c', result, maintenanceService);

		List<Date> targetLastDate = new List<Date>();
		for (Integer value : fromDate) {
			targetLastDate.add(Date.today() + value);
		}
		result = setVehicleField('Vehicle__c', 'Maintenance_from_date__c', result, targetLastDate);
		result = setVehicleField('Maintenance__c', 'Maintenance_status__c', result, status);
		result = setVehicleField('Maintenance__c', 'Vehicle__c', result, vehicle);
		return result;
	}
	/**
	 * create maintenance service
	 * @param n suffix for adress and name
	 * @param defaultService checkbox, create default service , or not
	 */
	public static Maintenance_Service__c createMaintenanceService(Integer n, Boolean defaultService) {
		Maintenance_Service__c maintenanceService = new Maintenance_Service__c();
		maintenanceService.Address__c = 'Adress ' + n;
		maintenanceService.Maintenance_default__c = Boolean.valueOf('False');
		maintenanceService.Name = 'testMaintenanceService_' + n;
		maintenanceService.Maintenance_default__c = defaultService;
		return maintenanceService;
	}
	/**
	 * builder for Contacts
	 * @param name requared field, name of contact
	 */
	public static List<Contact> createContacts(List<String> name) {
		List<Contact> result = new List<Contact>();
		result = setVehicleField('Contact', 'LastName', result, name);
		return result;
	}
	/**
	 * builder for Contacts
	 * @param name requared field, name of contact
	 * @param email email field. Caution, no validation!!!!!//TODO validation?
	 */
	public static List<Contact> createContacts(List<String> name, List<String> email) {
		List<Contact> result = createContacts(name);
		result = setVehicleField('Contact', 'Email', result, email);
		return result;
	}

	public static List<SObject> setVehicleField(
		String objectName,
		String objectField,
		List<sObject> target,
		List<String> value
	) {
		if (null == value || value.size() == 0) {
			return target;
		}
		// System.debug(
		// 	String.format(
		// 		' object name {0} field {1} target.size = {2} values size = {3}',
		// 		new List<Object>{ objectName, objectField, target.size(), value.size() }
		// 	)
		// );

		List<SObject> tmpResult = new List<sObject>();
		if (target.size() == 0) {
			for (String parameter : value) {
				Schema.SObjectType type = Schema.getGlobalDescribe().get(objectName);
				sObject vehicle = type.newSObject();
				vehicle.put(objectField, parameter);
				tmpResult.add(vehicle);
			}
		} else {
			for (SObject oldVehicle : target) {
				for (String parameter : value) {
					SObject vehicle = oldVehicle.clone();
					vehicle.put(objectField, parameter);
					tmpResult.add(vehicle);
				}
			}
		}
		return tmpResult;
	}

	public static List<SObject> setVehicleField(
		String objectName,
		String objectField,
		List<sObject> target,
		List<Date> value
	) {
		if (null == value || value.size() == 0) {
			return target;
		}
		// System.debug(
		// 	String.format(
		// 		' object name {0} field {1} target.size = {2} values size = {3}',
		// 		new List<Object>{ objectName, objectField, target.size(), value.size() }
		// 	)
		// );
		List<sObject> tmpResult = new List<sObject>();
		if (target.size() == 0) {
			for (Date parameter : value) {
				Schema.SObjectType type = Schema.getGlobalDescribe().get(objectName);
				sObject vehicle = type.newSObject();
				vehicle.put(objectField, (Date) parameter);
				tmpResult.add(vehicle);
			}
		} else {
			for (sObject oldVehicle : target) {
				for (Date parameter : value) {
					sObject vehicle = oldVehicle.clone();
					vehicle.put(objectField, parameter);
					tmpResult.add(vehicle);
				}
			}
		}
		return tmpResult;
	}

	public static List<SObject> setVehicleField(
		String objectName,
		String objectField,
		List<sObject> target,
		List<sObject> value
	) {
		if (null == value || value.size() == 0) {
			return target;
		}
		// System.debug(
		// 	String.format(
		// 		' object name {0} field {1} target.size = {2} values size = {3}',
		// 		new List<Object>{ objectName, objectField, target.size(), value.size() }
		// 	)
		// );
		List<sObject> tmpResult = new List<sObject>();
		if (target.size() == 0) {
			for (sObject parameter : value) {
				Schema.SObjectType type = Schema.getGlobalDescribe().get(objectName);
				sObject vehicle = type.newSObject();
				vehicle.put(objectField, parameter.Id);
				tmpResult.add(vehicle);
			}
		} else {
			for (SObject oldVehicle : target) {
				for (sObject parameter : value) {
					SObject vehicle = oldVehicle.clone();
					vehicle.put(objectField, parameter.Id);
					tmpResult.add(vehicle);
				}
			}
		}
		return tmpResult;
	}
}