force-app/main/default/objects/Maintenance__c/Maintenance__c.object-meta.xml
<CustomObject>
    <label>Maintenance</label>
    <nameField>
        <displayFormat>#{0}</displayFormat>
        <label>Maintenance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Maintenance&apos;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Maintenance__c/fields/Maintenance_from_date__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_from_date__c</fullName>
    <description>Maintenance is available from this date</description>
    <label>Maintenance from date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Maintenance__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <description>car that was serviced</description>
    <inlineHelpText>car that was serviced</inlineHelpText>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Maintenance&apos;s</relationshipLabel>
    <relationshipName>Maintenance_s</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <description>Basic vehicle type</description>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>ID#{000000}</displayFormat>
        <label>Vehicle ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_Last_Maintenance__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Last_Maintenance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle Last Maintenance</label>
    <referenceTo>Maintenance__c</referenceTo>
    <relationshipLabel>Vehicle</relationshipLabel>
    <relationshipName>Vehicle_Last_Maintenance</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_Last_Maintenance_Date__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Last_Maintenance_Date__c</fullName>
    <description>Vehicle Last Maintenance Date</description>
    <inlineHelpText>Last date of vehicle maintenance</inlineHelpText>
    <label>Vehicle Last Maintenance Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_Next_Maintenance_Date__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Next_Maintenance_Date__c</fullName>
    <description>Vehicle Next Maintenance Date</description>
    <inlineHelpText>Next sheduled date of vehicle maintenance</inlineHelpText>
    <label>Vehicle Next Maintenance Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/recordTypes/Vehicle.recordType-meta.xml
<RecordType>
    <fullName>Vehicle</fullName>
    <active>true</active>
    <label>Vehicle</label>
</RecordType>

force-app/main/default/classes/VehicleTrigger_Test.cls
@isTest
public with sharing class VehicleTrigger_Test {
	/**
	 * complex positive test, to validate single record creation
	 */
	@isTest
	private static void singleVehicleCreation_test() {
		VehicleTrigger_Test_Helper.makeSingleVehicle(true, false);
		List<Vehicle__c> resultVehicles = [SELECT Id, Vehicle_Next_Maintenance_Date__c FROM Vehicle__c];
		//check, that the vehicle record was created
		System.assert(resultVehicles.size() == 1, 'FAIL to create vehicle\n');
		List<Maintenance__c> resultMaintenance = [SELECT Id, Maintenance_from_date__c, Vehicle__c FROM Maintenance__c];

		System.debug('vehicles ' + resultVehicles.size() + 'maintenance ' + resultMaintenance.size());
		for (Maintenance__c maintenance : resultMaintenance) {
			System.debug(maintenance);
		}
		//check, that the record was created
		System.assert(resultMaintenance.size() == 1, 'FAIL to create maintenance\n');
		//check, that this is related records
		System.assert(
			resultVehicles.get(0).Id == resultMaintenance.get(0).Vehicle__c,
			'were created a vehicle and a maintenance records, they shoud be linked, but this does not happens'
		);
		System.assert(
			resultVehicles.get(0).Vehicle_Next_Maintenance_Date__c == resultMaintenance.get(0).Maintenance_from_date__c,
			'mismatch of the date of maintenance indicated in the record for the vehicle and maintenance'
		);
	}
	/**
	 * complex positive test, to validate many record creation
	 */
	@isTest
	private static void manyVehiclesCreation_test() {
		VehicleTrigger_Test_Helper.makeManyVehicles();

		Map<Id, Vehicle__c> vehiclesMap = new Map<Id, Vehicle__c>(
			[
				SELECT
					Id,
					Vehicle_Last_Maintenance_Date__c,
					Vehicle_Next_Maintenance_Date__c,
					Vehicle_Last_Maintenance__c
				FROM Vehicle__c
			]
		);
		System.debug('in test vehiclesMap size ' + vehiclesMap.size());
		System.assert(vehiclesMap.size() == VehicleTrigger_Test_Helper.NUMBER_OF_VALID_RECORDS);
		List<Maintenance__c> maintenanceList = [SELECT Id FROM Maintenance__c];
		System.debug('in test maintenanceList size ' + maintenanceList.size());
	}
}