force-app/main/default/objects/Maintenance__c/Maintenance__c.object-meta.xml
<CustomObject>
    <label>Maintenance</label>
    <nameField>
        <displayFormat>#{0}</displayFormat>
        <label>Maintenance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Maintenance&apos;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Maintenance__c/fields/Maintenance_due_date__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_due_date__c</fullName>
    <formula>Maintenance_from_date__c + 14</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Maintenance due date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Maintenance__c/fields/Maintenance_from_date__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_from_date__c</fullName>
    <description>Maintenance is available from this date</description>
    <label>Maintenance from date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Maintenance__c/fields/Maintenance_Service__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_Service__c</fullName>
    <label>Maintenance Service</label>
    <referenceTo>Maintenance_Service__c</referenceTo>
    <relationshipLabel>Maintenance&apos;s</relationshipLabel>
    <relationshipName>Maintenance_s</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Maintenance__c/fields/Maintenance_status__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_status__c</fullName>
    <label>Maintenance status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>POSTPONED, did not appear for inspection</fullName>
            </value>
            <value>
                <fullName>OK, all good</fullName>
            </value>
            <value>
                <fullName>OK, in-line repair</fullName>
            </value>
            <value>
                <fullName>BAD, capital repair</fullName>
            </value>
            <value>
                <fullName>BAD, only for spare parts</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Maintenance__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <description>car that was serviced</description>
    <inlineHelpText>car that was serviced</inlineHelpText>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Maintenance&apos;s</relationshipLabel>
    <relationshipName>Maintenance_s</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Maintenance_Service__c/Maintenance_Service__c.object-meta.xml
<CustomObject>
    <label>Maintenance Service</label>
    <nameField>
        <label>Maintenance Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Maintenance Service</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Maintenance_Service__c/fields/Maintenance_default__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_default__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This maintenance will be selected as default in approval process, if no service was on vehicle</description>
    <inlineHelpText>This maintenance will be selected as default in approval process, if no service was on vehicle</inlineHelpText>
    <label>Maintenance default</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <description>Basic vehicle type</description>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>ID#{000000}</displayFormat>
        <label>Vehicle ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_driver__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_driver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup for the contact of vehicle driver</description>
    <inlineHelpText>Vehicle driver conatct</inlineHelpText>
    <label>Vehicle driver</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Vehicle</relationshipLabel>
    <relationshipName>Vehicle</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_Last_Maintenance__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Last_Maintenance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle Last Maintenance</label>
    <referenceTo>Maintenance__c</referenceTo>
    <relationshipLabel>Vehicle</relationshipLabel>
    <relationshipName>Vehicle_Last_Maintenance</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_Last_Maintenance_Date__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Last_Maintenance_Date__c</fullName>
    <description>Vehicle Last Maintenance Date</description>
    <inlineHelpText>Last date of vehicle maintenance</inlineHelpText>
    <label>Vehicle Last Maintenance Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_model_description__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_model_description__c</fullName>
    <formula>Vehicle_Manufacturer__c &amp; &quot;:   &quot; &amp; Vehicle_model__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Vehicle model description</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_Next_Maintenance_Date__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Next_Maintenance_Date__c</fullName>
    <description>Vehicle Next Maintenance Date</description>
    <inlineHelpText>Next sheduled date of vehicle maintenance</inlineHelpText>
    <label>Vehicle Next Maintenance Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_plate_number__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_plate_number__c</fullName>
    <description>replace with vehicle number object</description>
    <label>Vehicle plate number</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/recordTypes/Vehicle.recordType-meta.xml
<RecordType>
    <fullName>Vehicle</fullName>
    <active>true</active>
    <label>Vehicle</label>
</RecordType>

force-app/main/default/triggers/VehicleTriggerHelper.cls
public class VehicleTriggerHelper {
	//resources
	public static List<Vehicle__c> targetVehicles = new List<Vehicle__c>();
	public static List<Maintenance__c> targetMaintenances = new List<Maintenance__c>();
	public static Map<Contact, String> targetDrivers = new Map<Contact, String>();

	public static final String MESSAGE_NEW_MAINTENANCE = 'new_mainanace';
	static final String MESSAGE_NEW_MAINTENANCE_BODY = 'New maintenance is scheduled for vehicle {0} from {1} to {2}';
	public static final String MESSAGE_STATUS_CHANGE = 'status_change';
	public static final String DATE_VALIDATION_ERROR =
		'Date validation error at the object Vehicle with ID {0} and description {1}.' +
		'The next maintenance date must be hightrer than the last maintenance date, but the last maintemamce date is {2} and the next is {3}';

	/**
	 * filter and validate values for the new maintenance process and update their Last Maintenance Date value
	 */
	public static void prepeareVehicleData(List<Vehicle__c> oldList, List<Vehicle__c> newList) {
		for (Vehicle__c vehicle : newList) {
			Vehicle__c oldVehicle = oldList.get(oldList.indexOf(vehicle));

			//filter, Next Maintenance Date is under update
			if (vehicle.Vehicle_Next_Maintenance_Date__c != oldVehicle.Vehicle_Next_Maintenance_Date__c) {
				//validate, Next Maintenance Date is on the future
				if (vehicle.Vehicle_Last_Maintenance_Date__c < oldVehicle.Vehicle_Next_Maintenance_Date__c) {
					//update
					vehicle.Vehicle_Last_Maintenance_Date__c = oldVehicle.Vehicle_Next_Maintenance_Date__c;
					targetVehicles.add(vehicle);
				} else {
					String errMsg = String.format(
						DATE_VALIDATION_ERROR,
						new List<Object>{
							vehicle.Id,
							vehicle.Vehicle_model_description__c,
							vehicle.Vehicle_Last_Maintenance_Date__c,
							vehicle.Vehicle_Next_Maintenance_Date__c
						}
					);
					Trigger.new.get(newList.indexOf(vehicle)).addError(errMsg);
				}
			}
		}
	}

	/**
	 * crate maintenance objects according to task
	 */
	public static void createMaintenanceRecords() {
		Maintenance_Service__c defaultServiecs = [
			SELECT Id
			FROM Maintenance_Service__c
			WHERE Maintenance_default__c = TRUE
			WITH SECURITY_ENFORCED
			LIMIT 1
		];

		//todo try-catch, read about
		for (Vehicle__c vehicle : targetVehicles) {
			Maintenance__c tmp = new Maintenance__c();
			tmp.Maintenance_from_date__c = vehicle.Vehicle_Next_Maintenance_Date__c;
			tmp.Maintenance_Service__c = vehicle.Vehicle_Last_Maintenance__c == null
				? defaultServiecs.Id
				: vehicle.Vehicle_Last_Maintenance__r.Maintenance_Service__c;
			tmp.Maintenance_status__c = 'Scheduled';
			tmp.Vehicle__c = vehicle.Id;
			vehicle.Vehicle_Last_Maintenance__c = tmp.Id;
			targetMaintenances.add(tmp);
		}
	}
	/**
	 * check, that the Driver exist in the Vehicle record, and have contact e-mail
	 * generate e-mail message to the valide drivers
	 */
	public static void prepeareDriversData(String type) {
		for (Vehicle__c vehicle : targetVehicles) {
			Contact driver = vehicle.Vehicle_driver__r;
			if (null == driver || driver.Email == '') {
				continue;
			}
			String msg = '';
			if (type == MESSAGE_NEW_MAINTENANCE) {
				msg = String.format(
					MESSAGE_NEW_MAINTENANCE_BODY,
					new List<Object>{
						vehicle.Vehicle_plate_number__c,
						vehicle.Vehicle_Last_Maintenance__r.Maintenance_from_date__c,
						vehicle.Vehicle_Last_Maintenance__r.Maintenance_due_date__c
					}
				);
			}
			if (type == MESSAGE_STATUS_CHANGE) {
				//TODO
			}

			if (msg.length() > 0)
				targetDrivers.put(driver, msg);
		}
	}

	public static void sendMessageToDrivers() {
		List<Messaging.SingleEmailMessage> mailToSent = new List<Messaging.SingleEmailMessage>(targetDrivers.size());
		for (Contact driver : targetDrivers.keySet()) {
			Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
			String[] toAddresses = new List<String>{ driver.Email };
			mail.setToAddresses(toAddresses);
			mail.setSubject('Vehicle manage - email to driver');
			mail.setPlainTextBody(targetDrivers.get(driver));
			mailToSent.add(mail);
		}

		Messaging.SendEmailResult[] results = Messaging.sendEmail(mailToSent);
		inspectResults(results);
	}

	// Public method
	void sendMail(String address, String subject, String body) {
		// Create an email message object
		Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
		String[] toAddresses = new List<String>{ address };
		mail.setToAddresses(toAddresses);
		mail.setSubject(subject);
		mail.setPlainTextBody(body);
		// Pass this email message to the built-in sendEmail method
		// of the Messaging class

		//!!!! List
		Messaging.SendEmailResult[] results = Messaging.sendEmail(new List<Messaging.SingleEmailMessage>{ mail });

		// Call a helper method to inspect the returned results
		inspectResults(results);
	}

	// Helper method
	private static Boolean inspectResults(Messaging.SendEmailResult[] results) {
		Boolean sendResult = true;

		// sendEmail returns an array of result objects.
		// Iterate through the list to inspect results.
		// In this class, the methods send only one email,
		// so we should have only one result.
		for (Messaging.SendEmailResult res : results) {
			if (res.isSuccess()) {
				System.debug('Email sent successfully');
			} else {
				sendResult = false;
				System.debug('The following errors occurred: ' + res.getErrors());
			}
		}

		return sendResult;
	}

	public static void saveMaintenanceRecords() {
		insert targetMaintenances;
	}

	public static void saveTargetVehicleRecords() {
		insert targetVehicles;
	}
}